'use strict';

/**@type {{[k: string]: TemplateData}} */
let BattlePokedex = {
cofagrigus: {
		num: 563,
		species: "Cofagrigus",
		types: ["Ghost", "Dark"],
		baseStats: {hp: 40, atk: 48, def: 180, spa: 92, spd: 100, spe: 40},
		abilities: {0: "Mummy", 1: "Rough Skin", H: "Cursed Body"},
		heightm: 1.7,
		weightkg: 76.5,
		color: "Yellow",
		eggGroups: ["Mineral", "Amorphous"],
	},
	nihilego: {
		num: 793,
		species: "Nihilego",
		types: ["Rock", "Poison"],
		gender: "N",
		baseStats: {hp: 101, atk: 83, def: 67, spa: 89, spd: 119, spe: 101},
		abilities: {0: "Beast Boost", H: "Unaware"},
		heightm: 1.2,
		weightkg: 55.5,
		color: "White",
		eggGroups: ["Undiscovered"],
	},
	raichu: {
		num: 26,
		species: "Raichu",
		types: ["Electric", "Ice"],
		baseStats: {hp: 55, atk: 105, def: 40, spa: 100, spd: 70, spe: 125},
		abilities: {0: "Static", 2: "Lightning Rod", H: "Magic Guard"},
		heightm: 0.8,
		weightkg: 30,
		color: "Yellow",
		eggGroups: ["Field", "Fairy"],
	},
flygon: {
		num: 330,
		species: "Flygon",
		types: ["Dragon", "Fairy"],
		baseStats: {hp: 85, atk: 50, def: 80, spa: 105, spd: 70, spe: 100},
		abilities: {0: "Mythical Presence"},
		heightm: 2,
		weightkg: 82,
		color: "Green",
		eggGroups: ["Bug"],
	},
meganium: {
		num: 154,
		species: "Meganium",
		types: ["Grass", "Dragon"],
		genderRatio: {M: 0.875, F: 0.125},
		baseStats: {hp: 82, atk: 83, def: 96, spa: 84, spd: 96, spe: 69},
		abilities: {0: "Thick Fat", 1: "Leaf Guard", H: "Solar Power"},
		heightm: 1.8,
		weightkg: 100.5,
		color: "Green",
		prevo: "bayleef",
		evoLevel: 32,
		eggGroups: ["Monster", "Grass"],
	},
tapubulu: {
		num: 787,
		species: "Tapu Bulu",
		types: ["Grass", "Fire"],
		gender: "N",
		baseStats: {hp: 85, atk: 85, def: 115, spa: 75, spd: 80, spe: 70},
		abilities: {0: "Grassy Surge", H: "Telepathy"},
		heightm: 1.9,
		weightkg: 45.5,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	metagross: {
		num: 376,
		species: "Metagross",
		types: ["Psychic", "Steel"],
		gender: "N",
		baseStats: {hp: 80, atk: 125, def: 105, spa: 65, spd: 65, spe: 75},
		abilities: {0: "Clear Body", H: "Iron Fist"},
		heightm: 1.6,
		weightkg: 550,
		color: "Blue",
		eggGroups: ["Mineral"],
	},
	cloyster: {
		num: 91,
		species: "Cloyster",
		types: ["Water", "Dark"],
		baseStats: {hp: 45, atk: 50, def: 180, spa: 75, spd: 55, spe: 80},
		abilities: {0: "Shell Armor", 1: "Intimidate", H: "Contrary"},
		heightm: 1.5,
		weightkg: 132.5,
		color: "Purple",
		eggGroups: ["Water 3"],
	},
	flaaffy: {
		num: 180,
		species: "Flaaffy",
		types: ["Electric", "Fairy"],
		baseStats: {hp: 100, atk: 55, def: 80, spa: 70, spd: 70, spe: 40},
		abilities: {0: "Natural Cure", 1: "Static", H: "Volt Absorb"},
		heightm: 0.8,
		weightkg: 13.3,
		color: "Pink",
        prevo: "mareep",
		evos: ["ampharos"],
		evoLevel: 15,
		eggGroups: ["Monster", "Field"],
	},
swalot: {
		num: 317,
		species: "Swalot",
		types: ["Poison", "Dark"],
		baseStats: {hp: 175, atk: 40, def: 65, spa: 80, spd: 65, spe: 50},
		abilities: {0: "Sticky Hold", 1: "Cheek Pouch", H: "Dry Skin"},
		heightm: 1.7,
		weightkg: 80,
		color: "Purple",
		eggGroups: ["Amorphous"],
	},
kricketune: {
		num: 402,
		species: "Kricketune",
		types: ["Bug", "Normal"],
		baseStats: {hp: 77, atk: 75, def: 61, spa: 75, spd: 61, spe: 95},
		abilities: {0: "Swarm", H: "Soundproof"},
		heightm: 1,
		weightkg: 25.5,
		color: "Red",
		eggGroups: ["Bug"],
	},
	poipole: {
		num: 803,
		species: "Poipole",
		types: ["Poison", "Psychic"],
		gender: "N",
		baseStats: {hp: 87, atk: 123, def: 67, spa: 123, spd: 67, spe: 63},
		abilities: {0: "Adaptability"},
		heightm: 0.6,
		weightkg: 1.8,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
	celesteela: {
		num: 797,
		species: "Celesteela",
		types: ["Steel"],
		gender: "N",
		baseStats: {hp: 97, atk: 97, def: 103, spa: 89, spd: 101, spe: 73},
		abilities: {0: "Beast Boost", H: "Force of Attraction"},
		heightm: 9.2,
		weightkg: 999.9,
		color: "Green",
		eggGroups: ["Undiscovered"],
	},
raticatealolatotem: {
		num: 20,
		species: "Raticate-Alola-Totem",
		formeLetter: "T",
		types: ["Dark", "Normal"],
		baseStats: {hp: 122, atk: 71, def: 40, spa: 40, spd: 50, spe: 77},
		abilities: {0: "Thick Fat", 1: "Gluttony", H: "Extreme Bulk"},
		heightm: 1.4,
		weightkg: 105,
		color: "Black",
		eggGroups: ["Field"],
	},
	rhydon: {
		num: 112,
		species: "Rhydon",
		types: ["Ground", "Rock"],
		baseStats: {hp: 115, atk: 130, def: 110, spa: 45, spd: 45, spe: 45},
		abilities: {0: "Lightning Rod", 1: "Thick Fat", H: "Mold Breaker"},
		heightm: 1.9,
		weightkg: 120,
		color: "Gray",
		prevo: "rhyhorn",
		evos: ["rhyperior"],
		evoLevel: 42,
		eggGroups: ["Monster", "Field"],
	},
	pangoro: {
		num: 675,
		species: "Pangoro",
		types: ["Fighting", "Dark"],
		baseStats: {hp: 81, atk: 110, def: 93, spa: 62, spd: 80, spe: 84},
		abilities: {0: "Iron Fist", 1: "Thick Fat", H: "Sap Sipper"},
		heightm: 2.1,
		weightkg: 136,
		color: "White",
		eggGroups: ["Field", "Human-Like"],
	},
	trapinch: {
		num: 328,
		species: "Trapinch",
		types: ["Ground", "Dark"],
		baseStats: {hp: 65, atk: 100, def: 65, spa: 45, spd: 65, spe: 10},
		abilities: {0: "Hyper Cutter", 1: "Arena Trap", H: "Mold Breaker"},
		heightm: 0.7,
		weightkg: 15,
		color: "Brown",
		eggGroups: ["Bug"],
	},
ninjask: {
		num: 291,
		species: "Ninjask",
		types: ["Water", "Flying"],
		baseStats: {hp: 70, atk: 60, def: 70, spa: 110, spd: 70, spe: 120},
		abilities: {0: "Infiltrator", H: "Technician"},
		heightm: 0.8,
		weightkg: 12,
		color: "Yellow",
		eggGroups: ["Bug"],
	},
	swampert: {
num: 260, 
species: "Swampert",
types:["Water", "Ground "],
baseStats: {hp: 100, atk: 100, def: 85, spa: 70, spd: 85, spe: 60}, 
abilities: {0: "Torrent", H: "Poison Heal"}, 
weightkg: 81.9,
},
swampertmega: {
num: 260, 
species: "Swampert-Mega",
types:["Water", "Ground "],
baseStats: {hp: 100, atk: 120, def: 110, spa: 90, spd: 110, spe: 70}, 
abilities: {0: "Sand Stream"}, 
weightkg: 102,
},
audino: {
num: 531, 
species: "Audino",
types:["Fairy", "Normal "],
baseStats: {hp: 125, atk: 60, def: 80, spa: 95, spd: 80, spe: 50}, 
abilities: {0: "Aroma Veil", 1: "Own Tempo", H: "Natural Cure"}, 
weightkg: 31,
},
audinomega: {
num: 531, 
species: "Audino-Mega",
types:["Fairy", "Normal "],
baseStats: {hp: 125, atk: 60, def: 110, spa: 135, spd: 110, spe: 50}, 
abilities: {0: "Misty Surge"}, 
weightkg: 32,
},
sharpedo: {
num: 319, 
species: "Sharpedo",
types:["Water", "Steel "],
baseStats: {hp: 60, atk: 100, def: 70, spa: 85, spd: 40, spe: 95}, 
abilities: {0: "Unnerve", 1: "Water Veil", H: "Moxie"}, 
weightkg: 88.8,
},
sharpedomega: {
num: 319, 
species: "Sharpedo-Mega",
types:["Water", "Fire "],
baseStats: {hp: 60, atk: 110, def: 70, spa: 145, spd: 60, spe: 105}, 
abilities: {0: "No Guard"}, 
weightkg: 103.3,
},

milotic: {
		num: 350,
		species: "Milotic",
		types: ["Water", "Fairy"],
		baseStats: {hp: 85, atk: 95, def: 90, spa: 85, spd: 90, spe: 95},
		abilities: {0: "Trace", 1: "Damp", H: "Hydration"},
		heightm: 6.2,
		weightkg: 162,
		color: "Pink",
		eggGroups: ["Water 1", "Dragon"],
	},
lanturn: {
		num: 171,
		species: "Lanturn",
		types: ["Water", "Electric"],
		baseStats: {hp: 125, atk: 40, def: 50, spa: 85, spd: 85, spe: 70},
		abilities: {0: "Water Absorb", 1: "Volt Absorb", H: "Abyssal Light"},
		heightm: 1.2,
		weightkg: 22.5,
		color: "Blue",
		eggGroups: ["Water 2"],
	},
toucannon: {
		num: 733,
		species: "Toucannon",
		types: ["Flying"],
		baseStats: {hp: 70, atk: 110, def: 110, spa: 75, spd: 75, spe: 55},
		abilities: {0: "Poison Heal", H: "Sheer Force"},
		heightm: 1.1,
		weightkg: 26,
		color: "Black",
		eggGroups: ["Flying"],
	},
mew: {
		num: 151,
		species: "Mew",
		types: ["Psychic", "Fairy"],
		gender: "N",
		baseStats: {hp: 85, atk: 85, def: 85, spa: 85, spd: 85, spe: 85},
		abilities: {0: "Prankster"},
		heightm: 0.4,
		weightkg: 4,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
};

exports.BattlePokedex = BattlePokedex;
