'use strict';

/**@type {{[k: string]: TemplateData}} */
let BattlePokedex = {
raichu: {
	inherit: true,
	species: "Raichu",
	types: ["Electric", "Light"],
	baseStats: {hp: 70, atk: 115, def: 60, spa: 90, spd: 80, spe: 130},
	abilities: {0: "Static", 1: "Quick Flash", H: "Lightning Rod"},
},
alolanraichu: {
	inherit: true,
	species: "Alolan Raichu",
	types: ["Electric", "Psychic"],
	baseStats: {hp: 70, atk: 90, def: 55, spa: 115, spd: 85, spe: 130},
	abilities: {0: "Contrary", 1: "Quick Flash", H: "Lightning Rod"},
},
wigglytuff: {
	inherit: true,
	species: "Wigglytuff",
	types: ["Sound", "Fairy"],
	baseStats: {hp: 140, atk: 70, def: 65, spa: 125, spd: 90, spe: 55},
	abilities: {0: "Dry Skin", 1: "Light Absorb", H: "Solar Power"},
},
crobat: {
	inherit: true,
	species: "Crobat",
	types: ["Blood", "Flying"],
	baseStats: {hp: 85, atk: 100, def: 80, spa: 70, spd: 80, spe: 130},
	abilities: {0: "Keen Eye", 1: "Skill Link", H: "Sheer Force"},
},
bellossom: {
	inherit: true,
	species: "Bellossom",
	types: ["Grass", "Light"],
	baseStats: {hp: 85, atk: 80, def: 95, spa: 100, spd: 110, spe: 55},
	abilities: {0: "Hyper Cutter", 1: "Iron Fist", H: "Anger Point"},
},
vileplume: {
	inherit: true,
	species: "Vileplume",
	types: ["Grass", "Poison"],
	baseStats: {hp: 85, atk: 80, def: 85, spa: 120, spd: 100, spe: 55},
	abilities: {0: "Illuminate", 1: "Effect Spore", H: "Rain Rish"},
},
primeape: {
	inherit: true,
	species: "Primeape",
	types: ["Fighting", "Blood"],
	baseStats: {hp: 75, atk: 125, def: 60, spa: 60, spd: 80, spe: 125},
	abilities: {0: "Leaf Guard", 1: "Queenly Majesty", H: "Sweet Veil"},
},
victreebel: {
	inherit: true,
	species: "Victreebel",
	types: ["Grass", "Poison"],
	baseStats: {hp: 80, atk: 115, def: 65, spa: 110, spd: 70, spe: 90},
	abilities: {0: "Hustle", 1: "Natural Cure", H: "Regenerator"},
},
lickilicky: {
	inherit: true,
	species: "Lickilicky",
	types: ["Food"],
	baseStats: {hp: 110, atk: 105, def: 100, spa: 85, spd: 100, spe: 50},
	abilities: {0: "Comatose"},
},
starmie: {
	inherit: true,
	species: "Starmie",
	types: ["Water", "Light"],
	baseStats: {hp: 70, atk: 75, def: 85, spa: 110, spd: 90, spe: 115},
	abilities: {0: "Speed Boost", 1: "Tinted Lens", H: "Frisk"},
},
jynx: {
	inherit: true,
	species: "Jynx",
	types: ["Ice", "Sound"],
	baseStats: {hp: 70, atk: 50, def: 55, spa: 125, spd: 95, spe: 115},
	abilities: {0: "Clear Body", 1: "Liquid Ooze", H: "Rain Dish"},
},
ledian: {
	inherit: true,
	species: "Ledian",
	types: ["Bug", "Light"],
	baseStats: {hp: 80, atk: 110, def: 70, spa: 55, spd: 110, spe: 105},
	abilities: {0: "Water Absorb", 1: "Shift Swim", H: "Hydration"},
},
lanturn: {
	inherit: true,
	species: "Lanturn",
	types: ["Water", "Light"],
	baseStats: {hp: 125, atk: 58, def: 68, spa: 116, spd: 116, spe: 67},
	abilities: {0: "Volt Absorb", 1: "Berserk", H: "Quick Feet"},
},
sunflora: {
	inherit: true,
	species: "Sunflora",
	types: ["Grass", "Light"],
	baseStats: {hp: 75, atk: 75, def: 65, spa: 115, spd: 85, spe: 90},
	abilities: {0: "Flash Fire", 1: "Defiant", H: "Toxic Boost"},
},
forretress: {
	inherit: true,
	species: "Forretress",
	types: ["Bug", "Steel"],
	baseStats: {hp: 85, atk: 90, def: 150, spa: 60, spd: 80, spe: 50},
	abilities: {0: "Synchronize", 1: "Forewarn", H: "Magic Bounce"},
},
mightyena: {
	inherit: true,
	species: "Mightyena",
	types: ["Dark", "Blood"],
	baseStats: {hp: 70, atk: 115, def: 70, spa: 60, spd: 80, spe: 110},
	abilities: {0: "Synchronize", 1: "Magic Guard", H: "Inner Focus"},
},
beautifly: {
	inherit: true,
	species: "Beautifly",
	types: ["Bug", "Blood"],
	baseStats: {hp: 70, atk: 100, def: 60, spa: 110, spd: 80, spe: 100},
	abilities: {0: "Leaf Guard", 1: "Regenerator", H: "Chlorophyll"},
},
dustox: {
	inherit: true,
	species: "Dustox",
	types: ["Bug", "Poison"],
	baseStats: {hp: 80, atk: 60, def: 100, spa: 100, spd: 110, spe: 70},
	abilities: {0: "Snow Cloak", 1: "Slush Rush", H: "Ice Body"},
},
masquerain: {
	inherit: true,
	species: "Masquerain",
	types: ["Bug", "Water"],
	baseStats: {hp: 80, atk: 60, def: 62, spa: 105, spd: 117, spe: 100},
	abilities: {0: "Cute Charm", 1: "Friend Guard", H: "Pixilate"},
},
exploud: {
	inherit: true,
	species: "Exploud",
	types: ["Sound"],
	baseStats: {hp: 104, atk: 111, def: 63, spa: 111, spd: 83, spe: 68},
	abilities: {0: ""},
},
hariyama: {
	inherit: true,
	species: "Hariyama",
	types: ["Fighting", "Food"],
	baseStats: {hp: 144, atk: 120, def: 70, spa: 40, spd: 95, spe: 50},
	abilities: {0: ""},
},
plusle: {
	inherit: true,
	species: "Plusle",
	types: ["Electric", "Blood"],
	baseStats: {hp: 70, atk: 50, def: 55, spa: 105, spd: 95, spe: 125},
	abilities: {0: ""},
},
minun: {
	inherit: true,
	species: "Minun",
	types: ["Electric", "Blood"],
	baseStats: {hp: 90, atk: 40, def: 75, spa: 75, spd: 115, spe: 105},
	abilities: {0: ""},
},
volbeat: {
	inherit: true,
	species: "Volbeat",
	types: ["Bug", "Light"],
	baseStats: {hp: 85, atk: 113, def: 75, spa: 97, spd: 85, spe: 90},
	abilities: {0: ""},
},
illumise: {
	inherit: true,
	species: "Illumise",
	types: ["Bug", "Light"],
	baseStats: {hp: 85, atk: 97, def: 75, spa: 113, spd: 85, spe: 90},
	abilities: {0: ""},
},
swalot: {
	inherit: true,
	species: "Swalot",
	types: ["Poison", "Food"],
	baseStats: {hp: 100, atk: 93, def: 103, spa: 93, spd: 103, spe: 55},
	abilities: {0: ""},
},
grumpig: {
	inherit: true,
	species: "Grumpig",
	types: ["Psychic", "Food"],
	baseStats: {hp: 80, atk: 45, def: 65, spa: 110, spd: 130, spe: 80},
	abilities: {0: ""},
},
zangoose: {
	inherit: true,
	species: "Zangoose",
	types: ["Normal", "Blood"],
	baseStats: {hp: 83, atk: 125, def: 70, spa: 100, spd: 70, spe: 90},
	abilities: {0: ""},
},
seviper: {
	inherit: true,
	species: "Seviper",
	types: ["Poison", "Blood"],
	baseStats: {hp: 83, atk: 115, def: 70, spa: 110, spd: 70, spe: 90},
	abilities: {0: ""},
},
tropius: {
	inherit: true,
	species: "Tropius",
	types: ["Flying", "Food"],
	baseStats: {hp: 119, atk: 68, def: 93, spa: 82, spd: 97, spe: 61},
	abilities: {0: ""},
},
chimecho: {
	inherit: true,
	species: "Chimecho",
	types: ["Psychic", "Sound"],
	baseStats: {hp: 85, atk: 50, def: 80, spa: 95, spd: 100, spe: 115},
	abilities: {0: ""},
},
clamperl: {
	inherit: true,
	species: "Clamperl",
	types: ["Water"],
	baseStats: {hp: 35, atk: 64, def: 85, spa: 74, spd: 65, spe: 32},
	abilities: {0: ""},
},
gorebyss: {
	inherit: true,
	species: "Gorebyss",
	types: ["Water", "Blood"],
	baseStats: {hp: 80, atk: 84, def: 105, spa: 114, spd: 75, spe: 72},
	abilities: {0: ""},
},
huntail: {
	inherit: true,
	species: "Huntail",
	types: ["Water", "Dark"],
	baseStats: {hp: 80, atk: 114, def: 105, spa: 84, spd: 75, spe: 72},
	abilities: {0: ""},
},
kricketune: {
	inherit: true,
	species: "Kricketune",
	types: ["Bug", "Sound"],
	baseStats: {hp: 97, atk: 115, def: 81, spa: 55, spd: 81, spe: 95},
	abilities: {0: ""},
},
sunshinecherrim: {
	inherit: true,
	species: "Sunshine Cherrim",
	types: ["Grass", "Light"],
	baseStats: {hp: 70, atk: 105, def: 70, spa: 117, spd: 88, spe: 100},
	abilities: {0: ""},
},
chatot: {
	inherit: true,
	species: "Chatot",
	types: ["Sound", "Flying"],
	baseStats: {hp: 76, atk: 65, def: 70, spa: 112, spd: 66, spe: 111},
	abilities: {0: ""},
},
lumineon: {
	inherit: true,
	species: "Lumineon",
	types: ["Water", "Light"],
	baseStats: {hp: 69, atk: 109, def: 76, spa: 109, spd: 86, spe: 91},
	abilities: {0: ""},
},
phione: {
	inherit: true,
	species: "Phione",
	types: ["Water", "Light"],
	baseStats: {hp: 90, atk: 100, def: 85, spa: 100, spd: 85, spe: 120},
	abilities: {0: ""},
},
emboar: {
	inherit: true,
	species: "Emboar",
	types: ["Fire", "Food"],
	baseStats: {hp: 110, atk: 123, def: 65, spa: 100, spd: 65, spe: 95},
	abilities: {0: ""},
},
watchog: {
	inherit: true,
	species: "Watchog",
	types: ["Light"],
	baseStats: {hp: 70, atk: 105, def: 69, spa: 105, spd: 69, spe: 127},
	abilities: {0: ""},
},
simisage: {
	inherit: true,
	species: "Simisage",
	types: ["Grass", "Food"],
	baseStats: {hp: 75, atk: 110, def: 63, spa: 110, spd: 63, spe: 111},
	abilities: {0: ""},
},
simisear: {
	inherit: true,
	species: "Simisear",
	types: ["Fire", "Food"],
	baseStats: {hp: 75, atk: 110, def: 63, spa: 110, spd: 63, spe: 111},
	abilities: {0: ""},
},
simipour: {
	inherit: true,
	species: "Simipour",
	types: ["Water", "Food"],
	baseStats: {hp: 75, atk: 110, def: 63, spa: 110, spd: 63, spe: 111},
	abilities: {0: ""},
},
audino: {
	inherit: true,
	species: "Audino",
	types: ["Sound"],
	baseStats: {hp: 103, atk: 60, def: 96, spa: 100, spd: 96, spe: 50},
	abilities: {0: ""},
	otherFormes: ["megaaudino"],
},
megaaudino: {
	inherit: true,
	species: "Mega Audino",
	baseSpecies: "Audino",
	forme: "Mega",
	formeLetter: "M",
	types: ["Sound", "Fairy"],
	baseStats: {hp: 103, atk: 60, def: 136, spa: 120, spd: 136, spe: 50},
	abilities: {0: ""},
},
conkeldurr: {
	inherit: true,
	species: "Conkeldurr",
	types: ["Fighting", "Blood"],
	baseStats: {hp: 105, atk: 140, def: 95, spa: 55, spd: 65, spe: 65},
	abilities: {0: ""},
},
seismitoad: {
	inherit: true,
	species: "Seismitoad",
	types: ["Water", "Sound"],
	baseStats: {hp: 105, atk: 115, def: 75, spa: 85, spd: 75, spe: 74},
	abilities: {0: ""},
},
lilligant: {
	inherit: true,
	species: "Lilligant",
	types: ["Grass", "Light"],
	baseStats: {hp: 80, atk: 60, def: 75, spa: 110, spd: 95, spe: 90},
	abilities: {0: ""},
},
cincinno: {
	inherit: true,
	species: "Cincinno",
	types: ["Normal", "Sound"],
	baseStats: {hp: 75, atk: 105, def: 70, spa: 65, spd: 70, spe: 125},
	abilities: {0: ""},
},
vanilluxe: {
	inherit: true,
	species: "Vanilluxe",
	types: ["Ice", "Food"],
	baseStats: {hp: 71, atk: 95, def: 85, spa: 110, spd: 95, spe: 89},
	abilities: {0: ""},
},
cryogonal: {
	inherit: true,
	species: "Cryogonal",
	types: ["Ice", "Light"],
	baseStats: {hp: 80, atk: 50, def: 70, spa: 105, spd: 135, spe: 105},
	abilities: {0: ""},
},
pyroar: {
	inherit: true,
	species: "Pyroar",
	types: ["Fire", "Sound"],
	baseStats: {hp: 86, atk: 108, def: 72, spa: 109, spd: 66, spe: 106},
	abilities: {0: ""},
},
slurpuff: {
	inherit: true,
	species: "Slurpuff",
	types: ["Fairy", "Food"],
	baseStats: {hp: 92, atk: 95, def: 86, spa: 95, spd: 75, spe: 72},
	abilities: {0: ""},
},
malamar: {
	inherit: true,
	species: "Malamar",
	types: ["Light", "Dark"],
	baseStats: {hp: 106, atk: 102, def: 88, spa: 68, spd: 105, spe: 73},
	abilities: {0: ""},
},
heliolisk: {
	inherit: true,
	species: "Heliolisk",
	types: ["Electric", "Light"],
	baseStats: {hp: 72, atk: 55, def: 62, spa: 119, spd: 94, spe: 109},
	abilities: {0: ""},
},
toucannon: {
	inherit: true,
	species: "Toucannon",
	types: ["Sound", "Flying"],
	baseStats: {hp: 90, atk: 130, def: 95, spa: 75, spd: 95, spe: 60},
	abilities: {0: ""},
},
crabominable: {
	inherit: true,
	species: "Crabominable",
	types: ["Fighting", "Ice"],
	baseStats: {hp: 97, atk: 132, def: 77, spa: 62, spd: 67, spe: 93},
	abilities: {0: ""},
},
shiinotic: {
	inherit: true,
	species: "Shiinotic",
	types: ["Grass", "Light"],
	baseStats: {hp: 80, atk: 75, def: 80, spa: 90, spd: 130, spe: 50},
	abilities: {0: ""},
},
tsareena: {
	inherit: true,
	species: "Tsareena",
	types: ["Grass", "Food"],
	baseStats: {hp: 72, atk: 120, def: 98, spa: 50, spd: 98, spe: 92},
	abilities: {0: ""},
},
corsola: {
	inherit: true,
	species: "Corsola",
	types: ["Water", "Rock"],
	baseStats: {hp: 75, atk: 55, def: 115, spa: 65, spd: 140, spe: 45},
	abilities: {0: ""},
},
komala: {
	inherit: true,
	species: "Komala",
	types: ["Normal"],
	baseStats: {hp: 85, atk: 115, def: 75, spa: 75, spd: 105, spe: 65},
	abilities: {0: ""},
},
yanmega: {
	inherit: true,
	species: "Yanmega",
	types: ["Bug", "Dragon"],
	baseStats: {hp: 86, atk: 76, def: 86, spa: 120, spd: 56, spe: 110},
	abilities: {0: ""},
},
tentacruel: {
	inherit: true,
	species: "Tentacruel",
	types: ["Water", "Poison"],
	baseStats: {hp: 80, atk: 80, def: 65, spa: 110, spd: 120, spe: 100},
	abilities: {0: ""},
},
vaporeon: {
	inherit: true,
	species: "Vaporeon",
	types: ["Water"],
	baseStats: {hp: 130, atk: 65, def: 60, spa: 110, spd: 95, spe: 85},
	abilities: {0: ""},
},
jolteon: {
	inherit: true,
	species: "Jolteon",
	types: ["Electric"],
	baseStats: {hp: 85, atk: 65, def: 60, spa: 110, spd: 95, spe: 130},
	abilities: {0: ""},
},
flareon: {
	inherit: true,
	species: "Flareon",
	types: ["Fire"],
	baseStats: {hp: 85, atk: 130, def: 60, spa: 95, spd: 110, spe: 65},
	abilities: {0: ""},
},
espeon: {
	inherit: true,
	species: "Espeon",
	types: ["Psychic"],
	baseStats: {hp: 85, atk: 65, def: 60, spa: 130, spd: 95, spe: 110},
	abilities: {0: ""},
},
umbreon: {
	inherit: true,
	species: "Umbreon",
	types: ["Dark"],
	baseStats: {hp: 95, atk: 65, def: 110, spa: 60, spd: 130, spe: 85},
	abilities: {0: ""},
},
leafeon: {
	inherit: true,
	species: "Leafeon",
	types: ["Grass"],
	baseStats: {hp: 85, atk: 110, def: 130, spa: 60, spd: 65, spe: 95},
	abilities: {0: ""},
},
glaceon: {
	inherit: true,
	species: "Glaceon",
	types: ["Ice"],
	baseStats: {hp: 85, atk: 60, def: 110, spa: 130, spd: 95, spe: 65},
	abilities: {0: ""},
},
sylveon: {
	inherit: true,
	species: "Sylveon",
	types: ["Fairy"],
	baseStats: {hp: 95, atk: 65, def: 85, spa: 110, spd: 130, spe: 60},
	abilities: {0: ""},
},

};

exports.BattlePokedex = BattlePokedex;
