'use strict';

/**@type {{[k: string]: {learnset: {[k: string]: MoveSource[]}}}} */
let BattleLearnsets = {
	thunderusa: {learnset: {
		doubleedge: ["5L1"],
		return: ["5L1"],
		wildcharge: ["5L1"],
		suckerpunch: ["5L1"],
		pursuit: ["5L1"],
		throatchop: ["5L1"],
		crunch: ["5L1"],
		knockoff: ["5L1"],
		powertrip: ["5L1"],
		earthquake: ["5L1"],
		superpower: ["5L1"],
		zenheadbutt: ["5L1"],
		ironhead: ["5L1"],
		voltswitch: ["5L1"],
		taunt: ["5L1"],
		bulkup: ["5L1"],
		thunderwave: ["5L1"],
	}},
  
  angealous: {learnset: {
		moonblast: ["5L1"],
		focusblast: ["5L1"],
		psychic: ["5L1"],
		aurasphere: ["5L1"],
		shadowball: ["5L1"],
		grassknot: ["5L1"],
		flashcannon: ["5L1"],
		incinerate: ["5L1"],
		vacuumwave: ["5L1"],
		airslash: ["5L1"],
		hex: ["5L1"],
		taunt: ["5L1"],
		calmmind: ["5L1"],
		workup: ["5L1"],
		roost: ["5L1"],
		toxic: ["5L1"],
		substitute: ["5L1"],
		defog: ["5L1"],
	}},
