thunderusa: {
		num: 805,
		species: "Thunderusa",
		types: ["Electric", "Dark"],
		baseStats: {hp: 90, atk: 120, def: 90, spa: 70, spd: 80, spe: 75},
		abilities: {0: "Gluttony", H: "Galvanize"},
		heightm: 1.5,
		weightkg: 120,
		eggGroups: ["Field"],
	},
  
  angealous: {
		num: 805,
		species: "Angealous",
		types: ["Fairy", "Fighting"],
    genderRatio: {M: 0.125, F: 0.875},
		baseStats: {hp: 85, atk: 60, def: 70, spa: 90, spd: 90, spe: 111},
		abilities: {0: "Cute Charm", 1: "Anger Point", H: "Sheer Force"},
		weightkg: 9,
		eggGroups: ["Fairy"],
	},
  
  contrunion: {
		num: 805,
		species: "Contrunion",
		types: ["Ice", "Fire"],
    genderRatio: "N",
		baseStats: {hp: 62, atk: 102, def: 42, spa: 102, spd: 42, spe: 142},
		abilities: {0: "Slush Rush", 1: "Solar Power", H: "Sheer Force"},
		weightkg: 9.6,
		eggGroups: ["Amorphous"],
	},
  
   cursphinx: {
		num: 805,
		species: "Cursphinx",
		types: ["Rock", "Ghost"],
    genderRatio: "N",
		baseStats: {hp: 68, atk: 78, def: 94, spa: 118, spd: 48, spe: 124},
		abilities: {0: "Sand Force", 1: "Cursed Body", H: "Levitate"},
		weightkg: 9.97,
		eggGroups: ["Amorphous"],
	},
  
   cryptech: {
		num: 805,
		species: "Cryptech",
		types: ["Steel", "Poison"],
    genderRatio: "N",
		baseStats: {hp: 83, atk: 71, def: 73, spa: 101, spd: 121, spe: 131},
		abilities: {0: "Datamining"},
		weightkg: 556.3,
		eggGroups: ["Undiscovered"],
	},
