naganadel: {
		num: 804,
		species: "Naganadel",
		types: ["Poison", "Dragon"],
		gender: "N",
		baseStats: {hp: 73, atk: 53, def: 83, spa: 179, spd: 83, spe: 129},
		abilities: {0: "Beast Boost"},
		heightm: 3.6,
		weightkg: 150,
		color: "Purple",
		prevo: "poipole",
		evoLevel: 41,
		eggGroups: ["Undiscovered"],
	},
 	mukalola: {
		num: 89,
		species: "Muk-Alola",
		baseSpecies: "Muk",
		forme: "Alola",
		formeLetter: "A",
		types: ["Poison", "Dark"],
		baseStats: {hp: 120, atk: 125, def: 125, spa: 70, spd: 115, spe: 45},
		abilities: {0: "Poison Touch", 1: "Gluttony", H: "Power of Alchemy"},
		heightm: 1,
		weightkg: 52,
		color: "Green",
		prevo: "grimeralola",
		evoLevel: 38,
		eggGroups: ["Amorphous"],
	},
tapukoko: {
		num: 785,
		species: "Tapu Koko",
		types: ["Electric", "Fairy"],
		gender: "N",
		baseStats: {hp: 70, atk: 150, def: 75, spa: 135, spd: 65, spe: 135},
		abilities: {0: "Electric Surge", H: "Telepathy"},
		heightm: 1.8,
		weightkg: 20.5,
		color: "Yellow",
		eggGroups: ["Undiscovered"],
	},
	tapulele: {
		num: 786,
		species: "Tapu Lele",
		types: ["Psychic", "Fairy"],
		gender: "N",
		baseStats: {hp: 105, atk: 70, def: 105, spa: 140, spd: 115, spe: 95},
		abilities: {0: "Psychic Surge", H: "Telepathy"},
		heightm: 1.2,
		weightkg: 18.6,
		color: "Pink",
		eggGroups: ["Undiscovered"],
	},
	tapubulu: {
		num: 787,
		species: "Tapu Bulu",
		types: ["Grass", "Fairy"],
		gender: "N",
		baseStats: {hp: 100, atk: 140, def: 130, spa: 80, spd: 110, spe: 70},
		abilities: {0: "Grassy Surge", H: "Telepathy"},
		heightm: 1.9,
		weightkg: 45.5,
		color: "Red",
		eggGroups: ["Undiscovered"],
	},
	tapufini: {
		num: 788,
		species: "Tapu Fini",
		types: ["Water", "Fairy"],
		gender: "N",
		baseStats: {hp: 100, atk: 70, def: 110, spa: 140, spd: 130, spe: 80},
		abilities: {0: "Misty Surge", H: "Telepathy"},
		heightm: 1.3,
		weightkg: 21.2,
		color: "Purple",
		eggGroups: ["Undiscovered"],
	},
