naganadel: {
		num: 804,
		species: "Naganadel",
		types: ["Poison", "Dragon"],
		gender: "N",
		baseStats: {hp: 73, atk: 53, def: 83, spa: 179, spd: 83, spe: 129},
		abilities: {0: "Beast Boost"},
		heightm: 3.6,
		weightkg: 150,
		color: "Purple",
		prevo: "poipole",
		evoLevel: 41,
		eggGroups: ["Undiscovered"],
	},
 
 	mukalola: {
		num: 89,
		species: "Muk-Alola",
		baseSpecies: "Muk",
		forme: "Alola",
		formeLetter: "A",
		types: ["Poison", "Dark"],
		baseStats: {hp: 120, atk: 125, def: 125, spa: 70, spd: 115, spe: 45},
		abilities: {0: "Poison Touch", 1: "Gluttony", H: "Power of Alchemy"},
		heightm: 1,
		weightkg: 52,
		color: "Green",
		prevo: "grimeralola",
		evoLevel: 38,
		eggGroups: ["Amorphous"],
	},
